<?php if (!defined('ABSPATH')) {
	die;
} // Cannot access directly.

/**
 * The Layout building class.
 */
class EFUL_Display
{

	/**
	 * Display options section metabox.
	 *
	 * @param string $prefix The metabox key.
	 * @return void
	 */
	public static function section($prefix)
	{
		EFUL::createSection(
			$prefix,
			array(
				'title'  => esc_html__('DISPLAY OPTIONS', 'eventful'),
				'icon'   => 'fas fa-th-large',
				'fields' => array(
					array(
						'id'         => 'section_title',
						'type'       => 'switcher',
						'title'      => esc_html__('Section Title ', 'eventful'),
						'subtitle'   => esc_html__('Show/Hide item showcase section title.', 'eventful'),
						'default'    => false,
						'text_on'    => esc_html__('Show', 'eventful'),
						'text_off'   => esc_html__('Hide', 'eventful'),
						'text_width' => 75,
					),
					array(
						'id'              => 'section_title_margin',
						'type'            => 'spacing',
						'title'           => esc_html__('Section Title Margin', 'eventful'),
						'subtitle'        => esc_html__('Set margin for the section title.', 'eventful'),
						'all_icon'        => '<i class="fas fa-long-arrow-down"></i>',
						'units'           => array(
							'px',
						),
						'all_placeholder' => 'margin',
						'default'         => array(
							'top'    => '0',
							'right'  => '0',
							'bottom' => '30',
							'top'    => '0',
						),
						'dependency'      => array(
							'section_title',
							'==',
							'true',
							true,
						),
					),
					array(
						'id'       => 'eful_number_of_columns',
						'type'     => 'column',
						'title'    => esc_html__('Column(s)', 'eventful'),
						'subtitle' => esc_html__('Set number of column(s) in different devices for responsive view.', 'eventful'),
						'default'  => array(
							'lg_desktop'       => '3',
							'desktop'          => '3',
							'tablet'           => '2',
							'mobile_landscape' => '2',
							'mobile'           => '1',
						),
						'min'      => '1',
						'dependency' => array('eful_layout_preset', 'any', 'carousel_layout,grid_layout,filter_layout,large_with_small', true),
						'help'       => wp_kses(esc_html__('<i class="fa fa-television"></i> <b> Large Desktop </b> - is larger than 1200px,<br><i class="fa fa-desktop"></i> <b>Desktop</b> - size is larger than 992px,<br> <i class="fa fa-tablet"></i> <b>Tablet</b> - Size is larger than 768,<br> <i class="fa fa-mobile"></i> <b> Mobile Landscape </b> - size is larger than 576px.,<br> <i class="fa fa-mobile"></i> <b> Mobile </b> - size is smaller than 576px.', 'eventful'), array('i' => array('class' => array()), 'br' => array())),
					),
					array(
						'id'              => 'margin_between_post',
						'type'            => 'spacing',
						'title'           => esc_html__('Margin Between Columns', 'eventful'),
						'subtitle'        => esc_html__('Set margin between columns (items).', 'eventful'),
						'all'             => true,
						'all_icon'        => '<i class="fas fa-arrows-h"></i>',
						'units'           => array(
							'px',
						),
						'all_placeholder' => 'margin',
						'default'         => array(
							'all' => '20',
						),
					),
					array(
						'id'       => 'post_content_orientation',
						'type'     => 'layout_preset',
						'title'    => esc_html__('Content Orientation ', 'eventful'),
						'subtitle' => esc_html__('Set a position for the item content.', 'eventful'),
						'desc'     => esc_html__('More amazing Content Orientation and Layout', 'eventful'),
						'class'    => 'eventful-content-orientation',
						'options'  => array(
							'default'     => array(
								'image' => EFUL_URL . 'admin/views/ta-framework/assets/images/default.png',
								'text'  => esc_html__('Default', 'eventful'),
							),
							'overlay'     => array(
								'image'    => EFUL_URL . 'admin/views/ta-framework/assets/images/overlay.png',
								'text'     => esc_html__('Overlay', 'eventful'),
								'pro_only' => true,
							),
						),
						'default'  => 'default',
						'dependency' => array('eful_layout_preset', 'any', 'carousel_layout,grid_layout,filter_layout,large_with_small', true),
					),
					array(
						'id'         => 'item_same_height',
						'type'       => 'checkbox',
						'title'      => esc_html__('Same Height', 'eventful'),
						'subtitle'   => esc_html__('Check to make all items/slides the same height as the tallest one.', 'eventful'),
						'default'    => false,
						'dependency' => array('eful_layout_preset', 'any', 'carousel_layout,grid_layout,filter_layout,large_with_small', true),
					),
					
					array(
						'id'       => 'post_border',
						'type'     => 'border',
						'title'    => esc_html__('Border', 'eventful'),
						'subtitle' => esc_html__('Set border for the item.', 'eventful'),
						'all'      => true,
						'default'  => array(
							'all'   => '0',
							'style' => 'solid',
							'color' => '#e2e2e2',
						),
					),
					array(
						'id'       => 'post_border_radius_property',
						'type'     => 'spacing',
						'title'    => esc_html__('Border Radius', 'eventful'),
						'subtitle' => esc_html__('Set border radius for item.', 'eventful'),
						'all'      => true,
						'units'    => array('px', '%'),
						'default'  => array(
							'all' => '0',
						),
					),
					array(
						'id'       => 'show_post_box_shadow',
						'type'     => 'checkbox',
						'title'    => esc_html__('Box-Shadow', 'eventful'),
						'subtitle' => esc_html__('Show box-shadow for the item.', 'eventful'),
						'default'  => false,
					),
					array(
						'id'         => 'post_box_shadow_property',
						'type'       => 'box_shadow',
						'title'      => esc_html__('Box-Shadow Values', 'eventful'),
						'subtitle'   => esc_html__('Set box-shadow property values for the item.', 'eventful'),
						'default'    => array(
							'horizontal' => '0',
							'vertical'   => '0',
							'blur'       => '8',
							'spread'     => '-2',
							'color'      => 'rgb(187, 187, 187)',
						),
						'dependency' => array('show_post_box_shadow', '==', 'true'),
					),
					array(
						'id'       => 'post_background_property',
						'type'     => 'color',
						'title'    => esc_html__('Background', 'eventful'),
						'subtitle' => esc_html__('Set background color for the item.', 'eventful'),
						'default'  => 'transparent',
						'dependency' => array('post_content_orientation', '!=', 'overlay'),
					),
					array(
						'id'       => 'post_background_overlay',
						'type'     => 'color',
						'title'    => esc_html__('Background', 'eventful'),
						'subtitle' => esc_html__('Set background color for the item. test', 'eventful'),
						'default'  => '#14141F',
						'dependency' => array('post_content_orientation', '==', 'overlay'),
					),
					array(
						'id'      => 'post_background_blur',
						'type'    => 'slider',
						'title'   => esc_html__('Slider', 'eventful'),
						'min'     => 0,
						'max'     => 9,
						'step'    => 1,
						'unit'    => '',
						'default' => 7,
						'dependency' => array('post_content_orientation', '==', 'overlay'),
					),

					array(
						'id'       => 'post_inner_padding_property',
						'type'     => 'spacing',
						'title'    => esc_html__('Inner Padding', 'eventful'),
						'subtitle' => esc_html__('Set inner padding for  item.', 'eventful'),
						'default'  => array(
							'top'    => '0',
							'right'  => '0',
							'bottom' => '0',
							'left'   => '0',
							'unit'   => 'px',
						),
						'help'     => "<img src='" . EFUL_URL . "/admin/assets/img/inner_padding.jpg'>",
					),
					array(
						'id'       => 'post_content_sorter',
						'type'     => 'sortable',
						'title'    => esc_html__('Content Fields', 'eventful'),
						'subtitle' => esc_html__('Item content fields which are draggable to change display order and it\'s settings.', 'eventful'),
						'class'    => 'post_content_sorter',
						'fields'   => array(
							array(
								'id'         => 'eful_post_thumb',
								'type'       => 'accordion',
								'accordions' => array(
									array(
										'title'  => esc_html__('Thumbnail', 'eventful'),
										'fields' => array(
											array(
												'id'       => 'post_thumb_show',
												'type'     => 'switcher',
												'title'    => esc_html__('Thumbnail', 'eventful'),
												'text_on'  => esc_html__('Show', 'eventful'),
												'text_off' => esc_html__('Hide', 'eventful'),
												'default'  => true,
												'text_width' => 80,
											),
											array(
												'id'      => 'eful_thumb_sizes',
												'type'    => 'image_sizes',
												'title'   => esc_html__('Size', 'eventful'),
												'default' => 'full',
												'dependency' => array('post_thumb_show', '==', 'true', true),
											),
											array(
												'id'       => 'eful_image_crop_size',
												'type'     => 'dimensions_advanced',
												'title'    => esc_html__('Custom Size', 'eventful'),
												'chosen'   => true,
												'bottom'   => false,
												'left'     => false,
												'color'    => false,
												'top_icon' => '<i class="fas fa-arrows-h"></i>',
												'right_icon' => '<i class="fas fa-arrows-v"></i>',
												'top_placeholder' => 'width',
												'right_placeholder' => 'height',
												'styles'   => array(
													'Soft-crop',
													'Hard-crop',
												),
												'default'  => array(
													'top'  => '600',
													'right' => '400',
													'style' => esc_html__('Soft-crop', 'eventful'),
													'unit' => 'px',
												),
												'attributes' => array(
													'min' => 0,
												),
												'dependency' => array('post_thumb_show|eful_thumb_sizes', '==|==', 'true|custom'),
											),
											array(
												'id'       => 'load_2x_image',
												'type'     => 'switcher',
												'title'    => esc_html__('Load 2x Resolution Image in Retina Display', 'eventful'),
												'text_on'  => esc_html__('Enabled', 'eventful'),
												'text_off' => esc_html__('Disabled', 'eventful'),
												'text_width' => 94,
												'default'  => false,
												'dependency' => array('post_thumb_show|eful_thumb_sizes', '==|==', 'true|custom'),
											),
											array(
												'id'       => 'post_thumb_margin',
												'type'     => 'spacing',
												'title'    => esc_html__('Margin', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'units'    => array('px'),
												'min'      => -100,
												'default'  => array(
													'top'  => '0',
													'right' => '0',
													'bottom' => '20',
													'left' => '0',
												),
												'dependency' => array('post_thumb_show', '==', 'true'),
											),
											array(
												'id'      => 'eful_thumb_src_replace',
												'type'    => 'checkbox',
												'title'   => esc_html__('Replace With', 'eventful'),
												'class'   => 'custom_help_text',
												'title_help' => esc_html__('This option will replace your default/featured post image with first resource ( image/video/audio ) from the content.', 'eventful'),
												'options' => array(
													'image'   => esc_html__('Image', 'eventful'),
													'video'   => esc_html__('Video', 'eventful'),
													'audio'   => esc_html__('Audio', 'eventful'),
												),
												'dependency' => array('post_thumb_show', '==', 'true'),
											),
											array(
												'id'      => 'post_featured_thumb_found',
												'type'    => 'select',
												'title'   => ' ',
												'options' => array(
													'no_featured_img_found' => esc_html__('If no featured image found', 'eventful'),
													'even_featured_img_found' => esc_html__('Even featured image was found', 'eventful'),
												),
												'default' => 'no_featured_img_found',
												'dependency' => array('post_thumb_show|eful_thumb_src_replace', '==|any', 'true|image,video,audio'),
											),

											array(
												'id'      => 'eful_thumb_border',
												'type'    => 'border',
												'title'   => esc_html__('Border', 'eventful'),
												'all'     => true,
												'default' => array(
													'all' => '0',
													'style' => 'solid',
													'color' => '#dddddd',
												),
												'dependency' => array('post_thumb_show', '==', 'true'),
											),
											array(
												'id'       => 'post_thumb_border_radius',
												'type'     => 'spacing',
												'title'    => esc_html__('Border Radius', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'default'  => array(
													'top'    => '0',
													'right'  => '0',
													'bottom' => '0',
													'left'   => '0',
													'unit'   => 'px',
												),
												'dependency' => array('post_thumb_show', '==', 'true'),
											),

											array(
												'id'      => 'post_thumb_zoom',
												'type'    => 'select',
												'title'   => esc_html__('Zoom Effect', 'eventful'),
												'options' => array(
													'none' => esc_html__('None', 'eventful'),
													'zoom_in' => esc_html__('Zoom In', 'eventful'),
													'zoom_out' => esc_html__('Zoom Out', 'eventful'),
												),
												'default' => 'none',
												'dependency' => array('post_thumb_show', '==', 'true'),
											),
											array(
												'id'      => 'post_thumb_gray_scale',
												'type'    => 'select',
												'title'   => esc_html__('Image Mode', 'eventful'),
												'options' => array(
													'none' => esc_html__('Normal', 'eventful'),
													'gray_and_normal' => esc_html__('Grayscale and normal on hover', 'eventful'),
													'gray_on_hover' => esc_html__('Grayscale on hover', 'eventful'),
													'always_gray' => esc_html__('Always grayscale', 'eventful'),
												),
												'default' => 'none',
												'dependency' => array('post_thumb_show', '==', 'true'),
											),
											array(
												'id'       => 'eful_img_lazy_load',
												'type'     => 'switcher',
												'class'    => 'custom_help_text',
												'title'    => esc_html__('Lazy Load', 'eventful'),
												'title_help' => esc_html__('Defer image loading to improve performance.', 'eventful'),
												'default'  => true,
												'text_on'  => esc_html__('Enabled', 'eventful'),
												'text_off' => esc_html__('Disabled', 'eventful'),
												'text_width' => 100,
												'dependency' => array('post_thumb_show|eful_layout_preset', '==|!=', 'true|carousel_layout', true),
											),
											array(
												'id'       => 'post_thumb_meta',
												'type'     => 'button_set',
												'title'   => esc_html__('Show Post Thumb Meta', 'eventful'),
												'default'  => true,
												'options'    => array(
													'category'  => esc_html__('Category', 'eventful'),
													'date' => esc_html__('Date', 'eventful'),
													'none' => esc_html__('None', 'eventful'),
												),
												'default'    => 'none',
												'dependency' => array('post_thumb_show', '==', 'true'),
											),
											array(
												'id'      => 'post_thumb_meta_taxonomy',
												'type'    => 'select',
												'title'   => esc_html__('Select Taxonomy', 'eventful'),
												'options' => 'taxonomy',
												'query_args' => array(
													'type' => 'post',
												),
												'attributes' => array(
													'style' => 'width: 200px;',
												),
												'empty_message' => esc_html__('No taxonomies found.', 'eventful'),
												'dependency' => array('post_thumb_show|post_thumb_meta', '==|==', 'true|category'),
											),
											array(
												'id'      => 'post_thumb_meta_date_format',
												'type'    => 'select',
												'title'   => esc_html__('Date Format', 'eventful'),
												'options' => array(
													'default' => esc_html__('Default', 'eventful'),
													'time_ago' => esc_html__('Time ago(human time)', 'eventful'),
													'custom' => esc_html__('Custom', 'eventful'),
												),
												'default' => 'default',
												'dependency' => array('select_post_meta', '==', 'date'),
											),
											array(
												'id'      => 'post_thumb_meta_position',
												'type'    => 'select',
												'title'   => esc_html__('Taxonomy Position', 'eventful'),
												'subtitle'   => esc_html__('Select a position for the navigation arrows.', 'eventful'),
												'options'    => array(
													'top_right'                   => esc_html__('Top right', 'eventful'),
													'top_center'                  => esc_html__('Top center', 'eventful'),
													'top_left'                    => esc_html__('Top left', 'eventful'),
													'bottom_left'                 => esc_html__('Bottom left', 'eventful'),
													'bottom_center'               => esc_html__('Bottom center', 'eventful'),
													'bottom_right'                => esc_html__('Bottom right', 'eventful'),
												),
												'default'    => 'top_right',
												'dependency' => array('post_thumb_show|post_thumb_meta', '==|!=', 'true|none'),
											),
											array(
												'id'      => 'post_thumb_meta_button',
												'type'    => 'color_group',
												'title'   => esc_html__('Read More Color', 'eventful'),
												'options' => array(
													'standard' => esc_html__('Text Color', 'eventful'),
													'hover' => esc_html__('Text Hover Color', 'eventful'),
													'bg' => esc_html__('Background', 'eventful'),
													'hover_bg' => esc_html__('Hover Background', 'eventful'),
													'border' => esc_html__('Border', 'eventful'),
													'hover_border' => esc_html__('Hover Border', 'eventful'),
												),
												'default' => array(
													'standard' => '#ffffff',
													'hover' => '#ffffff',
													'bg' => '#0015b5',
													'hover_bg' => '#263ad0',
													'border' => '#0015b5',
													'hover_border' => '#263ad0',
												),
												'dependency' => array('post_thumb_show|post_thumb_meta', '==|!=', 'true|none'),
											),
										),
									),
								),
							),
							array(
								'id'         => 'eful_post_title',
								'type'       => 'accordion',
								'accordions' => array(
									array(
										'title'  => esc_html__('Title', 'eventful'),
										'fields' => array(
											array(
												'id'       => 'show_post_title',
												'type'     => 'switcher',
												'title'    => esc_html__('Title', 'eventful'),
												'text_on'  => esc_html__('Show', 'eventful'),
												'text_off' => esc_html__('Hide', 'eventful'),
												'default'  => true,
												'text_width' => 80,
											),
											array(
												'id'      => 'post_title_tag',
												'type'    => 'select',
												'title'   => esc_html__('Title HTML Tag', 'eventful'),
												'options' => array(
													'h1'  => esc_html__('h1', 'eventful'),
													'h2'  => esc_html__('h2', 'eventful'),
													'h3'  => esc_html__('h3', 'eventful'),
													'h4'  => esc_html__('h4', 'eventful'),
													'h5'  => esc_html__('h5', 'eventful'),
													'h6'  => esc_html__('h6', 'eventful'),
													'p'   => esc_html__('p', 'eventful'),
													'div' => esc_html__('div', 'eventful'),
												),
												'default' => 'h2',
												'class'   => 'chosen',
												'dependency' => array('show_post_title', '==', 'true', true),
											),
											array(
												'id'      => 'post_title_limit',
												'type'    => 'checkbox',
												'title'   => esc_html__('Limit Character', 'eventful'),
												'default' => false,
												'dependency' => array('show_post_title', '==', 'true'),
											),
											array(
												'id'       => 'eful_title_length',
												'type'     => 'spinner',
												'title'    => esc_html__('Length', 'eventful'),
												'default'  => '30',
												'sanitize' => 'eful_sanitize_number_field',
												'unit'     => esc_html__('chars', 'eventful'),
												'dependency' => array('post_title_limit|show_post_title', '==|==', 'true|true'),
											),
											array(
												'id'       => 'post_title_margin',
												'type'     => 'spacing',
												'title'    => esc_html__('Margin', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'min'      => -100,
												'units'    => array('px'),
												'default'  => array(
													'top'  => '0',
													'right' => '0',
													'bottom' => '20',
													'left' => '0',
												),
												'dependency' => array('show_post_title', '==', 'true'),
											),
										),
									),
								),
							),

							array(
								'id'         => 'eful_post_meta',
								'class'      => 'eful_post_meta ta-product-not-fields',
								'type'       => 'accordion',
								'accordions' => array(
									array(
										'title'  => esc_html__('Meta Fields', 'eventful'),
										'fields' => array(
											array(
												'id'       => 'show_post_meta',
												'type'     => 'switcher',
												'title'    => esc_html__('Meta Fields', 'eventful'),
												'text_on'  => esc_html__('Show', 'eventful'),
												'text_off' => esc_html__('Hide', 'eventful'),
												'default'  => true,
												'text_width' => 80,
											),
											array(
												'id'      => 'eful_post_meta_group',
												'class'   => 'eful_custom_group_design',
												'type'    => 'group',
												'button_title' => esc_html__('Add New Meta', 'eventful'),
												'dependency' => array('show_post_meta', '==', 'true'),
												'fields'  => array(
													array(
														'id'       => 'select_post_meta',
														'class'       => 'select_post_meta',
														'type'     => 'select',
														'title'    => esc_html__('Select Meta', 'eventful'),
														'placeholder' => esc_html__('Select a meta', 'eventful'),
														'options'  => array(
															'author'  => esc_html__('Author', 'eventful'),
															'date'   => esc_html__('Date', 'eventful'),
															'taxonomy'   => esc_html__('Taxonomy', 'eventful'),
															'comment_count'  => esc_html__('Comment Count', 'eventful'),
															'view_count' => esc_html__('View Count', 'eventful'),
															'like'     => esc_html__('Like', 'eventful'),
															'reading_time'     => esc_html__('Reading Time', 'eventful'),
														),
													),
													array(
														'id'      => 'post_meta_author_avatar',
														'type'    => 'select',
														'title'   => esc_html__('Avatar', 'eventful'),
														'class'   => 'post_meta_author_avatar',
														'options' => array(
															'show_name' => esc_html__('Show name', 'eventful'),
															'show_gravatar' => esc_html__('Show gravatar', 'eventful'),
															'name_with_gravatar' => esc_html__('Author name & gravatar', 'eventful'),
															'name_with_icon' => esc_html__('Author name with an icon', 'eventful'),

														),
														'desc' => __('To show gravatar, you must <a href="https://wordpress.org/support/article/how-to-use-gravatars/" target="_blank" rel="noopener noreferrer nofollow"><em>enable it</em></a>.', 'eventful'),
														'default' => 'name_with_icon',
														'dependency' => array('select_post_meta', '==', 'author'),
													),
													array(
														'id'      => 'post_meta_date_format',
														'type'    => 'select',
														'title'   => esc_html__('Date Format', 'eventful'),
														'class'   => 'post_meta_date_format',
														'options' => array(
															'default' => esc_html__('Default', 'eventful'),
															'time_ago' => esc_html__('Time ago(human time)', 'eventful'),
															'custom' => esc_html__('Custom', 'eventful'),
														),
														'default' => 'default',
														'dependency' => array('select_post_meta', '==', 'date'),
													),
													array(
														'id'    => 'eful_custom_meta_date_format',
														'type'  => 'text',
														'title' => ' ',
														'class' => 'eful_custom_meta_date_format',
														'placeholder' => esc_html__('F j, Y', 'eventful'),
														'default'   => esc_html__('F j, Y', 'eventful'),
														'desc' => __('To define format, check <a href="https://wordpress.org/support/article/formatting-date-and-time/" target="_blank" rel="noopener noreferrer nofollow"><em>this doc</em></a>.', 'eventful'),
														'dependency' => array('select_post_meta|post_meta_date_format', '==|==', 'date|custom'),
													),
													array(
														'id'      => 'post_meta_taxonomy',
														'type'    => 'select',
														'title'   => esc_html__('Select Taxonomy', 'eventful'),
														'class'   => 'post_meta_taxonomy',
														'options' => 'taxonomy',
														'query_args' => array(
															'type' => 'post',
														),
														'attributes' => array(
															'style' => 'width: 200px;',
														),
														'empty_message' => esc_html__('No taxonomies found.', 'eventful'),
														'dependency' => array('select_post_meta', '==', 'taxonomy'),
													),
													array(
														'id'      => 'eful_meta_position',
														'class'      => 'eful_meta_position',
														'type'    => 'button_set',
														'title'   => esc_html__('Position', 'eventful'),
														'options' => array(
															'beside_meta' => esc_html__('Beside Other Meta', 'eventful'),
															'above_title' => esc_html__('Above Title', 'eventful'),
															'over_thumb' => esc_html__('Over Thumbnail', 'eventful'),

														),
														'default' => 'beside_meta',
														'dependency' => array('select_post_meta', '==', 'taxonomy'),
													),
													array(
														'id'      => 'eful_meta_over_thump_position',
														'type'    => 'select',
														'title'   => esc_html__('Over Thumbnail Position', 'eventful'),
														'options' => array(
															'top_left' => esc_html__('Top Left', 'eventful'),
															'top_right' => esc_html__('Top Right', 'eventful'),
															'bottom_left' => esc_html__('Bottom Left', 'eventful'),
															'bottom_right' => esc_html__('Bottom Right', 'eventful'),
														),
														'default' => 'top_left',
														'dependency' => array('select_post_meta|eful_meta_position', '==|==', 'taxonomy|over_thumb'),
													),
													array(
														'id'      => 'eful_meta_pill_color',
														'type'    => 'color_group',
														'title'   => esc_html__('Meta Color', 'eventful'),
														'options' => array(
															'text' => esc_html__('Text', 'eventful'),
															'bg' => esc_html__('Background', 'eventful'),
														),
														'default' => array(
															'text' => '#fff',
															'bg' => '#e53935',
														),
														'dependency' => array('select_post_meta|eful_meta_position', '==|!=', 'taxonomy|beside_meta'),
													),
													array(
														'id'      => 'eful_word_per_minute',
														'type'    => 'number',
														'title'   => esc_html__('Per Minute', 'eventful'),
														'class'   => 'eful_reading_time_meta',
														'title_help'   => esc_html__('Default 300 words, the average reading speed for adults.', 'eventful'),
														'sanitize'        => 'eful_sanitize_number_field',
														'unit'   => esc_html__('words', 'eventful'),
														'default' => '300',
														'dependency' => array('select_post_meta', '==', 'reading_time'),
														'default' => 300,
													),
													array(
														'id'      => 'select_meta_icon',
														'class'      => 'select_meta_icon',
														'type'    => 'icon',
														'title'   => esc_html__('Meta Icon', 'eventful'),
														'default' => 'far fa-folder',
														'dependency' => array('eful_meta_position|select_post_meta', '==|!=', 'beside_meta|like'),
													),
													array(
														'id'      => 'reading_time_postfix',
														'type'    => 'text',
														'title'   => esc_html__('Reading Time Postfix', 'eventful'),
														'class'   => 'eful_reading_time_postfix',
														'title_help'   => esc_html__('Text after time. Leave empty for nothing.', 'eventful'),
														'default' => esc_html(' Min Read', 'eventful'),
														'dependency' => array('select_post_meta', '==', 'reading_time'),
													),
												),
												'default' => array(
													array(
														'select_post_meta'    => 'author',
														'post_meta_author_avatar'    => 'name_with_icon',
														'select_meta_icon'    => 'fas fa-user',
														'eful_meta_position'     => 'beside_meta',
													),
													array(
														'select_post_meta'     => 'date',
														'select_meta_icon'    => 'fas fa-calendar',
														'eful_meta_position'     => 'beside_meta',
													),
													array(
														'select_post_meta'     => 'comment_count',
														'select_meta_icon'    => 'fas fa-calendar-alt',
														'eful_meta_position'     => 'beside_meta',
													),
												),
											),
											array(
												'id'      => 'meta_separator',
												'type'    => 'radio',
												'title'   => esc_html__('Meta Separator', 'eventful'),
												'options' => array(
													' '  => esc_html__('Normal Space ', 'eventful'),
													'. ' => esc_html__('Full Stop ( . ) ', 'eventful'),
													'| ' => esc_html__('Straight Line ( | )', 'eventful'),
													'/ ' => esc_html__('Slash ( / )', 'eventful'),
													'\ ' => esc_html__('Back Slash( \\ )', 'eventful'),
												),
												'default' => ' ',
												'dependency' => array('show_post_meta', '==', 'true'),
											),
											array(
												'id'      => 'meta_separator_color',
												'type'    => 'color',
												'title'   => esc_html__('Meta Separator Color', 'eventful'),
												'default' => '#0015b5',
												'dependency' => array('show_post_meta', '==', 'true'),
											),
											array(
												'id'      => 'post_meta_alignment',
												'type'    => 'button_set',
												'title'   => esc_html__( 'Alignment', 'eventful' ),
												'options' => array(
													'left' => wp_kses( __( '<i class="fas fa-align-left" title="Left"></i>', 'eventful' ), array( 'i' => array( 'class' => array() ) ) ),
													'center' => wp_kses( __( '<i class="fas fa-align-center" title="Center"></i>', 'eventful' ), array( 'i' => array( 'class' => array() ) ) ),
													'right' => wp_kses( __( '<i class="fas fa-align-right" title="Right"></i>', 'eventful' ), array( 'i' => array( 'class' => array() ) ) ),
												),
												'default' => 'left',
												'dependency' => array( 'show_post_meta', '==', 'true' ),
											),
											array(
												'id'       => 'post_meta_margin',
												'type'     => 'spacing',
												'title'    => esc_html__('Margin', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'units'    => array('px'),
												'min'      => -100,
												'dependency' => array('show_post_meta', '==', 'true'),
												'default'  => array(
													'top'  => '0',
													'right' => '0',
													'bottom' => '20',
													'left' => '0',
												),
											),
											array(
												'id'       => 'post_meta_between_margin',
												'type'     => 'spacing',
												'title'    => esc_html__('Margin Between Post Meta', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'units'    => array('px'),
												'min'      => -5,
												'dependency' => array('show_post_meta', '==', 'true'),
												'default'  => array(
													'top'  => '0',
													'right' => '0',
													'bottom' => '0',
													'left' => '0',
												),
											),
										),
									),
								),
							),
							array(
								'id'         => 'eful_event_fildes',
								'class'      => 'eful_event_fildes ta-product-not-fields',
								'type'       => 'accordion',
								'accordions' => array(
									array(
										'title'  => esc_html__('Event Fields', 'eventful'),
										'fields' => array(
											array(
												'id'       => 'show_event_fildes',
												'type'     => 'switcher',
												'title'    => esc_html__('Meta Fields', 'eventful'),
												'text_on'  => esc_html__('Show', 'eventful'),
												'text_off' => esc_html__('Hide', 'eventful'),
												'default'  => true,
												'text_width' => 80,
											),
											array(
												'id'      => 'eful_event_fildes_group',
												'class'   => 'eful_custom_group_design',
												'type'    => 'group',
												'button_title' => esc_html__('Add New Meta', 'eventful'),
												'dependency' => array('show_event_fildes', '==', 'true'),
												'fields'  => array(
													array(
														'id'       => 'select_event_fildes',
														'class'       => 'select_event_fildes',
														'type'     => 'select',
														'title'    => esc_html__('Select Meta', 'eventful'),
														'placeholder' => esc_html__('Select a meta', 'eventful'),
														'options'  => array(
															'venue'     => esc_html__('Venue', 'eventful'),
															'organizer'     => esc_html__('Organizer', 'eventful'),
															'price'     => esc_html__('Price', 'eventful'),
															'event_time'     => esc_html__('Event Time', 'eventful'),
														),
													),
													array(
														'id'       => 'venue_settings',
														'type'     => 'select',
														'title'    => esc_html__('Venue Settings', 'eventful'),
														'chosen'   => true,
														'sortable' => true,
														'multiple' => true,
														'placeholder' => esc_html__('Choose an option', 'eventful'),
														'options'  => array(
															'address' => esc_html__('Address', 'eventful'),
															'city' => esc_html__('City', 'eventful'),
															'country' => esc_html__('Country', 'eventful'),
															'state' => esc_html__('State', 'eventful'),
															'postal_code' => esc_html__('Postal Code', 'eventful'),
															'phone' => esc_html__('Phone', 'eventful'),
														),
														'default'     => array('address', 'city', 'country', 'postal_code', 'phone'),
														'dependency' => array('select_event_fildes', '==', 'venue'),
													),
													array(
														'id'      => 'venue_phone_icon',
														'type'    => 'icon',
														'title'   => esc_html__('Phone Icon', 'eventful'),
														'title_help'   => esc_html__('Set phone icon.', 'eventful'),
														'default' => 'fas fa-phone',
														'dependency' => array('venue_settings', 'any', 'phone'),
													),
													array(
														'id'      => 'venue_map_link',
														'type'    => 'switcher',
														'title'   => esc_html__('Show Map Link', 'eventful'),
														'class'   => 'venue_map_link',
														'title_help'   => esc_html__('Set show map link.', 'eventful'),
														'default' => true,
														'dependency' => array('venue_settings', 'any', 'address'),
													),
													array(
														'id'      => 'select_event_fildes_icon',
														'class'      => 'select_event_fildes_icon',
														'type'    => 'icon',
														'title'   => esc_html__('Meta Icon', 'eventful'),
														'default' => 'far fa-folder',
													),
													array(
														'id'      => 'event_fildes_date_type',
														'type'    => 'radio',
														'title'   => esc_html__('Date Type', 'eventful'),
														'class'   => 'event_fildes_date_type',
														'options' => array(
															'start_date' => esc_html__('Start Date and Time', 'eventful'),
															'end_date' => esc_html__('End Date and Time', 'eventful'),
															'start_date_time_with_end_date_time' => esc_html__('Start Date Time With End Date Time', 'eventful'),
														),
														'default' => 'start_date',
														'dependency' => array('select_event_fildes', '==', 'event_time'),
													),
													array(
														'id'    => 'event_fildes_date_format',
														'type'    => 'select',
														'title' => ' ',
														'class' => 'event_fildes_date_format',
														'options' => array(
															'j F, Y g:i A' => esc_html__('Default (01 January 2024 12:00 AM)', 'eventful'),
															'F j, Y g:i A' => esc_html__('Default (January 01 2024 12:00 AM)', 'eventful'),
															'F j, g:i A' => esc_html__('Default (January 01 12:00 AM)', 'eventful'),
															'j F, g:i A' => esc_html__('Default ( 01 January 12:00 AM)', 'eventful'),
															'j M, g:i A' => esc_html__('Default ( 01 Jan 12:00 AM)', 'eventful'),
															'M j, g:i A' => esc_html__('Default ( Jan 01 12:00 AM)', 'eventful'),
															'j F, Y' => esc_html__('Default (01 January 2024)', 'eventful'),
															'F j, Y' => esc_html__('Default (January 01 2024)', 'eventful'),
															'j F, Y' => esc_html__('Default (01 January 2024)', 'eventful'),
															'M j, Y' => esc_html__('Default (Jan 01 2024)', 'eventful'),
															'j M, Y' => esc_html__('Default (01 Jan 2024)', 'eventful'),
															'g:i A' => esc_html__('Default (12:50 AM)', 'eventful'),
															'G:i' => esc_html__('Default (23:00)', 'eventful'),
															'custom' => esc_html__('Custom', 'eventful'),
														),
														'default'   => esc_html__('j F, Y g:i A', 'eventful'),
														'desc' => __('To define format, check <a href="https://wordpress.org/support/article/formatting-date-and-time/" target="_blank" rel="noopener noreferrer nofollow"><em>this doc</em></a>.', 'eventful'),
														'dependency' => array('select_event_fildes', '==', 'event_time'),
													),
													array(
														'id'    => 'eful_custom_event_date_format',
														'type'  => 'text',
														'title' => ' ',
														'class' => 'eful_custom_event_date_format',
														'placeholder' => esc_html__('j F, Y g:i A', 'eventful'),
														'default'   => esc_html__('j F, Y g:i A', 'eventful'),
														'desc' => __('To define format, check <a href="https://wordpress.org/support/article/formatting-date-and-time/" target="_blank" rel="noopener noreferrer nofollow"><em>this doc</em></a>.', 'eventful'),
														'dependency' => array('select_event_fildes|event_fildes_date_format', '==|==', 'event_time|custom'),
													),
												),


												'default' => array(
													array(
														'select_event_fildes'    => 'venue',
														'select_event_fildes_icon'    => 'fas fa-map-marker-alt',
													),
													array(
														'select_event_fildes'     => 'event_time',
														'select_event_fildes_icon'    => 'far fa-clock',
													),
													array(
														'select_event_fildes'     => 'price',
														'select_event_fildes_icon'    => 'fas fa-money-check-alt',
													),
												),
											),
											array(
												'id'      => 'event_meta_separator',
												'type'    => 'radio',
												'title'   => esc_html__('Event Meta Separator', 'eventful'),
												'options' => array(
													' '  => esc_html__('Normal Space ', 'eventful'),
													'. ' => esc_html__('Full Stop ( . ) ', 'eventful'),
													'| ' => esc_html__('Straight Line ( | )', 'eventful'),
													'/ ' => esc_html__('Slash ( / )', 'eventful'),
													'\ ' => esc_html__('Back Slash( \\ )', 'eventful'),
												),
												'default' => ' ',
												'dependency' => array('show_event_fildes', '==', 'true'),
											),
											array(
												'id'      => 'event_meta_separator_color',
												'type'    => 'color',
												'title'   => esc_html__('Event Meta Separator Color', 'eventful'),
												'default' => '#0015b5',
												'dependency' => array('show_event_fildes', '==', 'true'),
											),
											array(
												'id'      => 'event_meta_alignment',
												'type'    => 'button_set',
												'title'   => esc_html__( 'Alignment', 'eventful' ),
												'options' => array(
													'left' => wp_kses( __( '<i class="fas fa-align-left" title="Left"></i>', 'eventful' ), array( 'i' => array( 'class' => array() ) ) ),
													'center' => wp_kses( __( '<i class="fas fa-align-center" title="Center"></i>', 'eventful' ), array( 'i' => array( 'class' => array() ) ) ),
													'right' => wp_kses( __( '<i class="fas fa-align-right" title="Right"></i>', 'eventful' ), array( 'i' => array( 'class' => array() ) ) ),
												),
												'default' => 'left',
												'dependency' => array( 'show_event_fildes', '==', 'true' ),
											),
											array(
												'id'       => 'event_fildes_margin',
												'type'     => 'spacing',
												'title'    => esc_html__('Margin', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'units'    => array('px'),
												'min'      => -100,
												'dependency' => array('show_event_fildes', '==', 'true'),
												'default'  => array(
													'top'  => '0',
													'right' => '0',
													'bottom' => '20',
													'left' => '0',
												),
											),
											array(
												'id'       => 'event_fildes_between_margin',
												'type'     => 'spacing',
												'title'    => esc_html__('Margin Between Post Meta', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'units'    => array('px'),
												'min'      => -5,
												'dependency' => array('show_event_fildes', '==', 'true'),
												'default'  => array(
													'top'  => '0',
													'right' => '0',
													'bottom' => '0',
													'left' => '0',
												),
											),
										),
									),
								),
							),
							array(
								'id'         => 'eful_post_content',
								'type'       => 'accordion',
								'accordions' => array(
									array(
										'title'  => esc_html__('Content', 'eventful'),
										'fields' => array(
											array(
												'id'       => 'show_post_content',
												'type'     => 'switcher',
												'title'    => esc_html__('Content', 'eventful'),
												'text_on'  => esc_html__('Show', 'eventful'),
												'text_off' => esc_html__('Hide', 'eventful'),
												'default'  => true,
												'text_width' => 80,
											),
											array(
												'id'      => 'post_content_type',
												'type'    => 'select',
												'title'   => esc_html__('Content Display Type', 'eventful'),
												'options' => array(
													'excerpt'      => esc_html__('Excerpt', 'eventful'),
													'limit_content' => esc_html__('Content with Limit', 'eventful'),
													'full_content' => esc_html__('Full Content', 'eventful'),
												),
												'default' => 'limit_content',
												'dependency' => array('show_post_content', '==', 'true'),
											),
											array(
												'id'      => 'eful_content_length_type',
												'type'    => 'button_set',
												'title'   => esc_html__('Content Length Type', 'eventful'),
												'options' => array(
													'words'    => esc_html__('Words', 'eventful'),
													'characters' => esc_html__('Characters', 'eventful'),
												),
												'default' => 'words',
												'dependency' => array('show_post_content|post_content_type', '==|==', 'true|limit_content'),
											),
											array(
												'id'       => 'eful_content_limit',
												'type'     => 'spinner',
												'title'    => esc_html__('Words Length', 'eventful'),
												'sanitize' => 'eful_sanitize_number_field',
												'default'  => 30,
												'max'      => 10000,
												'dependency' => array('show_post_content|post_content_type|eful_content_length_type', '==|==|==', 'true|limit_content|words'),
											),
											array(
												'id'       => 'eful_content_characters_limit',
												'type'     => 'spinner',
												'title'    => esc_html__('Characters Length', 'eventful'),
												'sanitize' => 'eful_sanitize_number_field',
												'default'  => 300,
												'max'      => 10000,
												'dependency' => array('show_post_content|post_content_type|eful_content_length_type', '==|==|==', 'true|limit_content|characters'),
											),
											array(
												'id'       => 'post_content_margin',
												'type'     => 'spacing',
												'title'    => esc_html__('Margin', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'units'    => array('px'),
												'min'      => -100,
												'default'  => array(
													'top'  => '0',
													'right' => '0',
													'bottom' => '20',
													'left' => '0',
												),
												'dependency' => array('show_post_content', '==', 'true'),
											),
											array(
												'id'      => 'eful_strip_tags',
												'type'    => 'radio',
												'title'   => esc_html__('HTML Tags', 'eventful'),
												'options' => array(
													'allow_all'  => esc_html__('Allow All', 'eventful'),
													'strip_all'  => esc_html__('Strip All', 'eventful'),
													'allow_some' => esc_html__('Allow Some', 'eventful'),
												),
												'default' => 'allow_all',
												'dependency' => array('show_post_content|post_content_type', '==|!=', 'true|excerpt'),
											),
											array(
												'id'    => 'eful_allow_tag_name',
												'type'  => 'text',
												'title' => esc_html__('Allow HTML Tags Names', 'eventful'),
												'title_help' => esc_html__('Separate multiple tags by comma, e.g. h1,h2', 'eventful'),
												'dependency' => array('show_post_content|eful_strip_tags', '==|==', 'true|allow_some'),
											),
											array(
												'id'      => 'post_content_ellipsis',
												'type'    => 'text',
												'title'   => esc_html__('Ellipsis Points Ending Excerpt', 'eventful'),
												'default' => '...',
												'dependency' => array('show_post_content|post_content_type', '==|!=', 'true|full_content'),
											),
										),
									),
								),
							),
							array(
								'id'         => 'eful_post_content_readmore',
								'type'       => 'accordion',
								'accordions' => array(
									array(
										'title'  => esc_html('Read more', 'eventful'),
										'fields' => array(
											// ReadMore settings.
											array(
												'id'       => 'show_read_more',
												'type'     => 'switcher',
												'title'    => esc_html__('Read More', 'eventful'),
												'text_on'  => esc_html__('Show', 'eventful'),
												'text_off' => esc_html__('Hide', 'eventful'),
												'default'  => true,
												'text_width' => 80,
											),
											array(
												'id'      => 'read_more_type',
												'type'    => 'button_set',
												'title'   => esc_html__('Read More Type', 'eventful'),
												'options' => array(
													'button'    => esc_html__('Button', 'eventful'),
													'text_link' => esc_html__('Text Link', 'eventful'),
												),
												'default' => 'button',
												'dependency' => array('show_read_more', '==', 'true'),
											),
											array(
												'id'      => 'eful_read_label',
												'type'    => 'text',
												'title'   => esc_html__('Read More Label', 'eventful'),
												'default' => 'Read More',
												'dependency' => array('show_read_more', '==', 'true'),
											),
											array(
												'id'      => 'readmore_color_button',
												'type'    => 'color_group',
												'title'   => esc_html__('Read More Color', 'eventful'),
												'options' => array(
													'standard' => esc_html__('Text Color', 'eventful'),
													'hover' => esc_html__('Text Hover Color', 'eventful'),
													'bg' => esc_html__('Background', 'eventful'),
													'hover_bg' => esc_html__('Hover Background', 'eventful'),
													'border' => esc_html__('Border', 'eventful'),
													'hover_border' => esc_html__('Hover Border', 'eventful'),
												),
												'default' => array(
													'standard' => '#ffffff',
													'hover' => '#ffffff',
													'bg' => '#0015b5',
													'hover_bg' => '#263ad0',
													'border' => '#0015b5',
													'hover_border' => '#263ad0',
												),
												'dependency' => array('show_read_more|read_more_type', '==|==', 'true|button'),
											),
											array(
												'id'       => 'readmore_padding',
												'type'     => 'spacing',
												'title'    => esc_html__('Padding', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'units'    => array('px'),
												'min'      => -100,
												'default'  => array(
													'top'  => '6',
													'right' => '20',
													'bottom' => '6',
													'left' => '20',
												),
												'dependency' => array('show_read_more|read_more_type', '==|==', 'true|button'),
											),
											array(
												'id'       => 'readmore_margin',
												'type'     => 'spacing',
												'title'    => esc_html__('Margin', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'units'    => array('px'),
												'min'      => -100,
												'default'  => array(
													'top'  => '0',
													'right' => '0',
													'bottom' => '20',
													'left' => '0',
												),
												'dependency' => array('show_read_more', '==', 'true'),
											),
											array(
												'id'       => 'readmore_button_radius',
												'type'     => 'spacing',
												'title'    => esc_html__('Border Radius', 'eventful'),
												'sanitize' => 'eful_sanitize_number_array_field',
												'all'      => true,
												'default'  => array(
													'all'  => '0',
													'unit' => 'px',
												),
												'units'    => array('px', '%'),
												'dependency' => array('show_read_more|read_more_type', '==|==', 'true|button'),
											),
											array(
												'id'      => 'readmore_color_text',
												'type'    => 'color_group',
												'title'   => esc_html__('Read More Color', 'eventful'),
												'options' => array(
													'standard' => esc_html__('Text Color', 'eventful'),
													'hover' => esc_html__('Text Hover Color', 'eventful'),
												),
												'default' => array(
													'standard' => '#ffffff',
													'hover' => '#0015b5',
												),
												'dependency' => array('show_read_more|read_more_type', '==|==', 'true|text_link'),
											),

										),
									),
								),
							),
						),
					),
					array(
						'id'         => 'show_post_pagination',
						'type'       => 'switcher',
						'text_on'    => esc_html__('Enabled', 'eventful'),
						'text_off'   => esc_html__('Disabled', 'eventful'),
						'text_width' => 100,
						'title'      => esc_html__('Pagination', 'eventful'),
						'subtitle'   => esc_html__('Enabled/Disabled item pagination.', 'eventful'),
						'default'    => true,
						'dependency' => array('eful_layout_preset', '!=', 'carousel_layout', true),
					),
					array(
						'id'         => 'post_pagination_type',
						'type'       => 'radio',
						'title'      => esc_html__('Pagination Type', 'eventful'),
						'subtitle'   => esc_html__('Choose a pagination type.', 'eventful'),
						'options'    => array(
							'ajax_load_more'  => esc_html__('Load More Button (Ajax)', 'eventful'),
							'ajax_pagination' => esc_html__('Ajax Number Pagination', 'eventful'),
							'infinite_scroll' => esc_html__('Infinite Scroll (Ajax)', 'eventful'),
							'no_ajax'         => esc_html__('No Ajax (Normal Pagination)', 'eventful'),
						),
						'default'    => 'ajax_load_more',
						'dependency' => array('eful_layout_preset|show_post_pagination', 'not-any|==', 'carousel_layout,filter_layout|true', true),
					),
					array(
						'id'         => 'filter_pagination_type',
						'type'       => 'radio',
						'title'      => esc_html__('Filter Pagination Type', 'eventful'),
						'subtitle'   => esc_html__('Choose a pagination type.', 'eventful'),
						'options'    => array(
							'ajax_load_more'  => esc_html__('Load More Button (Ajax)', 'eventful'),
							'infinite_scroll' => esc_html__('Infinite Scroll (Ajax)', 'eventful'),
						),
						'default'    => 'ajax_load_more',
						'dependency' => array('eful_layout_preset|show_post_pagination', '==|==', 'filter_layout|true', true),
					),
					array(
						'id'         => 'post_pagination_type_mobile',
						'type'       => 'select',
						'title'      => esc_html__('Pagination Type for Mobile', 'eventful'),
						'subtitle'   => esc_html__('Choose a pagination type for mobile view.', 'eventful'),
						'options'    => array(
							'ajax_load_more'  => esc_html__('Load More Button (Ajax)', 'eventful'),
							'ajax_pagination' => esc_html__('Ajax Pagination', 'eventful'),
							'infinite_scroll' => esc_html__('Infinite Scroll (Ajax)', 'eventful'),
							'no_ajax'         => esc_html__('No Ajax (Normal Pagination)', 'eventful'),
						),
						'default'    => 'infinite_scroll',
						'dependency' => array('eful_layout_preset|show_post_pagination', 'not-any|==', 'carousel_layout,filter_layout|true', true),
					),
					array(
						'id'         => 'load_more_button_text',
						'type'       => 'text',
						'title'      => esc_html__('Load More Button Label', 'eventful'),
						'subtitle'   => esc_html__('Set the label for load more button.', 'eventful'),
						'default'    => esc_html__('Load More', 'eventful'),
						'dependency' => array('eful_layout_preset|show_post_pagination', '!=|==', 'carousel_layout|true', true),
					),
					array(
						'id'         => 'load_more_ending_message',
						'type'       => 'text',
						'title'      => esc_html__('Ending Message', 'eventful'),
						'subtitle'   => esc_html__('Set ending message for load more/infinite scroll.', 'eventful'),
						'default'    => esc_html__('No more events available', 'eventful'),
						'dependency' => array('eful_layout_preset|show_post_pagination', '!=|==', 'carousel_layout|true', true),
					),
					array(
						'id'         => 'eful_pagination_btn_color',
						'type'       => 'color_group',
						'title'      => esc_html__('Pagination  Color', 'eventful'),
						'subtitle'   => esc_html__('Set Pagination color', 'eventful'),
						'options'    => array(
							'text_color'        => esc_html__('Text Color', 'eventful'),
							'text_acolor'       => esc_html__('Text Active Color', 'eventful'),
							'border_color'      => esc_html__('Border Color', 'eventful'),
							'border_acolor'     => esc_html__('Border Active Color', 'eventful'),
							'background'        => esc_html__('Background', 'eventful'),
							'active_background' => esc_html__('Active BG', 'eventful'),
						),
						'default'    => array(
							'text_color'        => '#5e5e5e',
							'text_acolor'       => '#ffffff',
							'border_color'      => '#bbbbbb',
							'border_acolor'     => '#0015b5',
							'background'        => '#ffffff',
							'active_background' => '#0015b5',
						),
						'dependency' => array('eful_layout_preset|show_post_pagination|post_pagination_type', '!=|==|any', 'carousel_layout|true|ajax_pagination,no_ajax', true),
					),
					array(
						'id'         => 'eful_loadmore_btn_color',
						'type'       => 'color_group',
						'title'      => esc_html__('Load More Button Color', 'eventful'),
						'subtitle'   => esc_html__('Set load more button color.', 'eventful'),
						'options'    => array(
							'text_color'        => esc_html__('Text Color', 'eventful'),
							'text_hcolor'       => esc_html__('Text hover Color', 'eventful'),
							'background'        => esc_html__('Background', 'eventful'),
							'active_background' => esc_html__('Hover Background', 'eventful'),
						),
						'default'    => array(
							'text_color'        => '#ffffff',
							'text_hcolor'       => '#5e5e5e',
							'background'        => '#0015b5',
							'active_background' => '#ffffff',
						),
						'dependency' => array('eful_layout_preset|show_post_pagination|post_pagination_type', '!=|==|==', 'carousel_layout|true|ajax_load_more', true),
					),
					array(
						'id'         => 'pagination_alignment',
						'type'       => 'button_set',
						'title'      => esc_html__('Alignment', 'eventful'),
						'subtitle'   => esc_html__('Choose pagination alignment.', 'eventful'),
						'options'    => array(
							'left'   => wp_kses(__('<i class="fas fa-align-left" title="Left"></i>', 'eventful'), array('i' => array('class' => array()))),
							'center' => wp_kses(__('<i class="fas fa-align-center" title="Center"></i>', 'eventful'), array('i' => array('class' => array()))),
							'right'  => wp_kses(__('<i class="fas fa-align-right" title="Right"></i>', 'eventful'), array('i' => array('class' => array()))),
						),
						'default'    => 'left',
						'dependency' => array('eful_layout_preset|show_post_pagination', '!=|==', 'carousel_layout|true', true),
					),
					array(
						'id'         => 'post_per_page',
						'type'       => 'spinner',
						'title'      => esc_html__('Items Per Page', 'eventful'),
						'subtitle'   => esc_html__('Set number of items to show per page.', 'eventful'),
						'title_help' => esc_html__('This value should be lesser than that <strong> Limit </strong> from <strong>Filter Content  </strong> tab.', 'eventful'),
						'sanitize'   => 'eful_sanitize_number_field',
						'default'    => 12,
						'dependency' => array('eful_layout_preset|show_post_pagination', '!=|==', 'carousel_layout|true', true),
					),
					array(
						'id'         => 'show_preloader',
						'type'       => 'switcher',
						'title'      => esc_html__('Preloader', 'eventful'),
						'subtitle'   => esc_html__('Items will be hidden until page load completed.', 'eventful'),
						'text_on'    => esc_html__('Enabled', 'eventful'),
						'text_off'   => esc_html__('Disabled', 'eventful'),
						'text_width' => 100,
						'default'    => false,
					),
					array(
						'type'    => 'subheading',
						'class'   => 'eful_filter_btn_color hidden',
						'content' => esc_html__('Live Filter Button', 'eventful'),
					),
				), // End of fields array.
			)
		); // Display settings section end.
	}
}
