<?php if (!defined('ABSPATH')) {
	die;
} // Cannot access directly.

/**
 * The Carousel building class.
 */
class EFP_Carousel
{

	/**
	 * Carousel section metabox.
	 *
	 * @param string $prefix The metabox key.
	 * @return void
	 */
	public static function section($prefix)
	{
		EFP::createSection(
			$prefix,
			array(
				'title'  => esc_html__( 'Carousel Controls', 'eventful' ),
				'icon'   => 'fas fa-sliders-h',
				'fields' => array(
					array(
						'id'       => 'efp_carousel_mode',
						'type'     => 'button_set',
						'title'    => esc_html__( 'Carousel Mode', 'eventful' ),
						'subtitle' => esc_html__( 'Choose a mode for the carousel.', 'eventful' ),
						'options'  => array(
							'standard' => esc_html__( 'Standard', 'eventful' ),
							'center'   => esc_html__( 'Center', 'eventful' ),
							'ticker'   => esc_html__( 'Ticker', 'eventful' ),
						),
						'default'  => 'standard',
					),
					array(
						'id'         => 'efp_ticker_speed',
						'type'       => 'spinner',
						'title'      => esc_html__( 'Carousel Speed', 'eventful' ),
						'subtitle'   => esc_html__( 'Set carousel speed in millisecond.', 'eventful' ),
						'sanitize'   => 'efp_sanitize_number_field',
						'default'    => '3000',
						'min'        => 0,
						'max'        => 50000,
						'step'       => 100,
						'unit'       => 'ms',
						'dependency' => array( 'efp_carousel_mode', '==', 'ticker' ),
					),

					array(
						'id'         => 'efp_ticker_slide_width',
						'type'       => 'spinner',
						'title'      => esc_html__( 'Column Width', 'eventful' ),
						'subtitle'   => esc_html__( 'Set a width for the column.', 'eventful' ),
						'sanitize'   => 'efp_sanitize_number_field',
						'default'    => '250',
						'min'        => 0,
						'max'        => 1000,
						'step'       => 10,
						'unit'       => 'px',
						'dependency' => array( 'efp_carousel_mode', '==', 'ticker' ),
					),
					array(
						'id'         => 'efp_autoplay',
						'type'       => 'switcher',
						'title'      => esc_html__( 'AutoPlay', 'eventful' ),
						'subtitle'   => esc_html__( 'Enable/Disable carousel autoplay.', 'eventful' ),
						'text_on'    => esc_html__( 'Enabled', 'eventful' ),
						'text_off'   => esc_html__( 'Disabled', 'eventful' ),
						'text_width' => 94,
						'default'    => true,
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'efp_autoplay_speed',
						'type'       => 'spinner',
						'title'      => esc_html__( 'AutoPlay Speed', 'eventful' ),
						'subtitle'   => esc_html__( 'Set autoplay speed in millisecond.', 'eventful' ),
						'sanitize'   => 'efp_sanitize_number_field',
						'default'    => '2000',
						'min'        => 0,
						'max'        => 10000,
						'step'       => 100,
						'unit'       => 'ms',
						'dependency' => array( 'efp_autoplay|efp_carousel_mode', '==|!=', 'true|ticker' ),
					),
					array(
						'id'         => 'efp_carousel_speed',
						'type'       => 'spinner',
						'title'      => esc_html__( 'Carousel Speed', 'eventful' ),
						'subtitle'   => esc_html__( 'Set carousel speed in millisecond.', 'eventful' ),
						'sanitize'   => 'efp_sanitize_number_field',
						'default'    => '600',
						'min'        => 0,
						'max'        => 20000,
						'step'       => 100,
						'unit'       => 'ms',
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'efp_pause_hover',
						'type'       => 'switcher',
						'title'      => esc_html__( 'Pause on Hover', 'eventful' ),
						'subtitle'   => esc_html__( 'Enable/Disable carousel stop on hover.', 'eventful' ),
						'text_on'    => esc_html__( 'Enabled', 'eventful' ),
						'text_off'   => esc_html__( 'Disabled', 'eventful' ),
						'text_width' => 94,
						'default'    => true,
						'dependency' => array( 'efp_autoplay', '==', 'true' ),
					),
					array(
						'id'         => 'efp_infinite_loop',
						'type'       => 'switcher',
						'title'      => esc_html__( 'Infinite Loop', 'eventful' ),
						'subtitle'   => esc_html__( 'Enable/Disable carousel infinite loop.', 'eventful' ),
						'text_on'    => esc_html__( 'Enabled', 'eventful' ),
						'text_off'   => esc_html__( 'Disabled', 'eventful' ),
						'text_width' => 94,
						'default'    => true,
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'efp_lazy_load',
						'type'       => 'switcher',
						'title'      => esc_html__( 'Lazy Load', 'eventful' ),
						'subtitle'   => esc_html__( 'Enable/Disable lazy load.', 'eventful' ),
						'text_on'    => esc_html__( 'Enabled', 'eventful' ),
						'text_off'   => esc_html__( 'Disabled', 'eventful' ),
						'text_width' => 94,
						'default'    => true,
						'dependency' => array( 'efp_carousel_mode|efp_slide_effect', '!=|not-any', 'ticker|cube,flip' ),
					),
					array(
						'id'       => 'efp_carousel_direction',
						'type'     => 'button_set',
						'title'    => esc_html__( 'Carousel Direction', 'eventful' ),
						'subtitle' => esc_html__( 'Choose a carousel direction.', 'eventful' ),
						'options'  => array(
							'ltr' => esc_html__( 'Right to Left', 'eventful' ),
							'rtl' => esc_html__( 'Left to Right', 'eventful' ),
						),
						'default'  => 'ltr',
					),
					array(
						'id'         => 'efp_slide_effect',
						'type'       => 'select',
						'title'      => esc_html__( 'Transition Effect', 'eventful' ),
						'subtitle'   => esc_html__( 'Select a slide transition effect.', 'eventful' ),
						'help'       => esc_html__( 'Fade, cube, and flip transition effects work only for the single column view.', 'eventful' ),
						'options'    => array(
							'slide'     => esc_html__( 'Slide', 'eventful' ),
							'fade'      => esc_html__( 'Fade', 'eventful' ),
							'coverflow' => esc_html__( 'Coverflow', 'eventful' ),
							'cube'      => esc_html__( 'Cube', 'eventful' ),
							'flip'      => esc_html__( 'Flip', 'eventful' ),
						),
						'default'    => 'slide',
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'efp_number_of_row',
						'type'       => 'column',
						'title'      => esc_html__( 'Row', 'eventful' ),
						'subtitle'   => esc_html__( 'Set number of row in different devices for responsive view.', 'eventful' ),
						'default'    => array(
							'lg_desktop'       => '1',
							'desktop'          => '1',
							'tablet'           => '1',
							'mobile_landscape' => '1',
							'mobile'           => '1',
						),
						'min'        => '1',
						'dependency' => array( 'efp_carousel_mode', '==', 'standard', true ),
						'help'       => esc_html__( 'When multiple <b>Row</b> is set, the above two options <b>Infinite Loop</b> and <b>Auto Height</b> won\'t work properly.', 'eventful' ),
					),
					array(
						'type'       => 'subheading',
						'content'    => esc_html__( 'Navigation', 'eventful' ),
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					// Navigation Settings.
					array(
						'id'         => 'efp_navigation',
						'type'       => 'button_set',
						'title'      => esc_html__( 'Navigation', 'eventful' ),
						'subtitle'   => esc_html__( 'Show/Hide carousel navigation.', 'eventful' ),
						'options'    => array(
							'show'           => esc_html__( 'Show', 'eventful' ),
							'hide'           => esc_html__( 'Hide', 'eventful' ),
							'hide_on_mobile' => esc_html__( 'Hide on Mobile', 'eventful' ),
						),
						'default'    => 'show',
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'efp_carousel_nav_position',
						'type'       => 'select',
						'title'      => esc_html__( 'Select Position', 'eventful' ),
						'subtitle'   => esc_html__( 'Select a position for the navigation arrows.', 'eventful' ),
						'options'    => array(
							'top_right'                   => esc_html__( 'Top right', 'eventful' ),
							'top_center'                  => esc_html__( 'Top center', 'eventful' ),
							'top_left'                    => esc_html__( 'Top left', 'eventful' ),
							'bottom_left'                 => esc_html__( 'Bottom left', 'eventful' ),
							'bottom_center'               => esc_html__( 'Bottom center', 'eventful' ),
							'bottom_right'                => esc_html__( 'Bottom right', 'eventful' ),
							'vertically_center_outer'     => esc_html__( 'Vertically center outer', 'eventful' ),
							'vertical_center_inner'       => esc_html__( 'Vertically center inner', 'eventful' ),
							'vertical_center_inner_hover' => esc_html__( 'Vertically center inner on hover', 'eventful' ),
						),
						'default'    => 'top_right',
						'dependency' => array( 'efp_navigation|efp_carousel_mode', '!=|!=', 'hide|ticker' ),
					),
					array(
						'id'         => 'navigation_icons',
						'type'       => 'button_set',
						'title'      => esc_html__( 'Choose an Icon', 'eventful' ),
						'subtitle'   => esc_html__( 'Choose a carousel navigation icon.', 'eventful' ),
						'options'    => array(
							'fa-angle'        => '<i class="fas fa-angle-right"></i>',
							'fa-angle-double' => '<i class="fas fa-angle-right"></i>',
							'fa-arrow'        => '<i class="fas fa-arrow-right"></i>',
							'fa-caret'        => '<i class="fas fa-caret-right"></i>',
							'fa-chevron'      => '<i class="fas fa-chevron-right"></i>',
						),
						'default'    => 'fa-angle',
						'dependency' => array( 'efp_navigation|efp_carousel_mode', '!=|!=', 'hide|ticker' ),
					),
					array(
						'id'         => 'efp_nav_icon_size',
						'type'       => 'spinner',
						'title'      => esc_html__( 'Arrow Icon Size', 'eventful' ),
						'subtitle'   => esc_html__( 'Set a size for arrow icon.', 'eventful' ),
						'sanitize'   => 'efp_sanitize_number_field',
						'default'    => '18',
						'min'        => 0,
						'max'        => 100,
						'unit'       => 'px',
						'dependency' => array( 'efp_navigation|efp_carousel_mode', '!=|!=', 'hide|ticker' ),
					),
					array(
						'id'         => 'navigation_icons_border_radius',
						'type'       => 'spacing',
						'title'      => esc_html__( 'Navigation Border Radius', 'eventful' ),
						'subtitle'   => esc_html__( 'Set border radius for the navigation icons.', 'eventful' ),
						'sanitize'   => 'efp_sanitize_number_array_field',
						'all'        => true,
						'min'        => 0,
						'max'        => 100,
						'units'      => array( 'px', '%' ),
						'default'    => array(
							'all' => '0',
						),
						'dependency' => array( 'efp_navigation|efp_carousel_mode', '!=|!=', 'hide|ticker' ),
					),
					array(
						'id'         => 'efp_nav_colors',
						'type'       => 'color_group',
						'title'      => esc_html__( 'Navigation Color', 'eventful' ),
						'subtitle'   => esc_html__( 'Set color for the carousel navigation.', 'eventful' ),
						'options'    => array(
							'color'              => esc_html__( 'Color', 'eventful' ),
							'hover-color'        => esc_html__( 'Hover Color', 'eventful' ),
							'bg'                 => esc_html__( 'Background', 'eventful' ),
							'hover-bg'           => esc_html__( 'Hover Background', 'eventful' ),
							'border-color'       => esc_html__( 'Border', 'eventful' ),
							'hover-border-color' => esc_html__( 'Hover Border', 'eventful' ),
						),
						'default'    => array(
							'color'              => '#aaa',
							'hover-color'        => '#fff',
							'bg'                 => '#fff',
							'hover-bg'           => '#263ad0',
							'border-color'       => '#aaa',
							'hover-border-color' => '#263ad0',
						),
						'dependency' => array( 'efp_navigation|efp_carousel_mode', '!=|!=', 'hide|ticker' ),
					),

					// Pagination Settings.
					array(
						'type'       => 'subheading',
						'content'    => esc_html__( 'Pagination', 'eventful' ),
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'efp_pagination',
						'type'       => 'button_set',
						'title'      => esc_html__( 'Pagination', 'eventful' ),
						'subtitle'   => esc_html__( 'Show/Hide carousel pagination.', 'eventful' ),
						'options'    => array(
							'show'           => esc_html__( 'Show', 'eventful' ),
							'hide'           => esc_html__( 'Hide', 'eventful' ),
							'hide_on_mobile' => esc_html__( 'Hide on Mobile', 'eventful' ),
						),
						'default'    => 'show',
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'bullet_types',
						'type'       => 'button_set',
						'title'      => esc_html__( 'Pagination Type', 'eventful' ),
						'subtitle'   => esc_html__( 'Choose a type for pagination.', 'eventful' ),
						'options'    => array(
							'dots'   => esc_html__( 'Dots', 'eventful' ),
							'number' => esc_html__( 'Number', 'eventful' ),
						),
						'default'    => 'dots',
						'dependency' => array( 'efp_pagination|efp_carousel_mode', '!=|!=', 'hide|ticker' ),
					),
					array(
						'id'         => 'efp_pagination_color_set',
						'type'       => 'fieldset',
						'class'      => 'efp-pagination-color-set',
						'title'      => esc_html__( 'Pagination Color', 'eventful' ),
						'subtitle'   => esc_html__( 'Set color for the carousel pagination.', 'eventful' ),
						'fields'     => array(
							array(
								'id'         => 'efp_pagination_color',
								'type'       => 'color_group',
								'options'    => array(
									'color'        => esc_html__( 'Color', 'eventful' ),
									'active-color' => esc_html__( 'Active Color', 'eventful' ),
								),
								'default'    => array(
									'color'        => '#cccccc',
									'active-color' => '#263ad0',
								),
								'dependency' => array( 'bullet_types', '==', 'dots', true ),
							),
							array(
								'id'         => 'efp_pagination_number_color',
								'type'       => 'color_group',
								'options'    => array(
									'color'       => esc_html__( 'Color', 'eventful' ),
									'hover-color' => esc_html__( 'Hover Color', 'eventful' ),
									'bg'          => esc_html__( 'Background', 'eventful' ),
									'hover-bg'    => esc_html__( 'Hover Background', 'eventful' ),
								),
								'default'    => array(
									'color'       => '#ffffff',
									'hover-color' => '#ffffff',
									'bg'          => '#444444',
									'hover-bg'    => '#263ad0',
								),
								'dependency' => array( 'bullet_types', '==', 'number', true ),
							),
						),
						'dependency' => array( 'efp_pagination|efp_carousel_mode', '!=|!=', 'hide|ticker' ),
					),
					array(
						'id'         => 'efp_dynamicBullets',
						'type'       => 'checkbox',
						'title'      => esc_html__( 'Dynamic Pagination', 'eventful' ),
						'subtitle'   => esc_html__( 'Check to show dynamic pagination.', 'eventful' ),
						'default'    => false,
						'dependency' => array( 'efp_pagination|efp_carousel_mode', '!=|!=', 'hide|ticker' ),
					),
					array(
						'id'         => 'efp_slides_to_scroll',
						'type'       => 'column',
						'title'      => esc_html__( 'Slide To Scroll', 'eventful' ),
						'subtitle'   => esc_html__( 'Number of post(s) to scroll at a time.', 'eventful' ),
						'unit'       => false,
						'default'    => array(
							'lg_desktop' => '1',
							'desktop'    => '1',
							'laptop'     => '1',
							'tablet'     => '1',
							'mobile'     => '1',
						),
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
						'help'       => wp_kses(esc_html__('<i class="fas fa-television"></i> <b> Large Desktop </b> - is larger than 1200px,<br><i class="fas fa-desktop"></i> <b>Desktop</b> - size is larger than 992px,<br> <i class="fas fa-tablet-alt"></i> <b>Tablet</b> - Size is larger than 768,<br> <i class="fas fa-mobile-alt"></i> <b> Mobile Landscape </b> - size is larger than 576px.,<br> <i class="fas fa-mobile-alt"></i> <b> Mobile </b> - size is smaller than 576px.', 'eventful'), array('i' => array('class' => array()), 'br' => array()) ),
					),
					// Miscellaneous Settings.
					array(
						'type'       => 'subheading',
						'content'    => esc_html__( 'Miscellaneous', 'eventful' ),
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'efp_adaptive_height',
						'type'       => 'switcher',
						'title'      => esc_html__( 'Adaptive Carousel Height', 'eventful' ),
						'subtitle'   => esc_html__( 'Dynamically adjust post carousel height based on each slide\'s height.', 'eventful' ),
						'default'    => false,
						'text_on'    => esc_html__( 'Enabled', 'eventful' ),
						'text_off'   => esc_html__( 'Disabled', 'eventful' ),
						'text_width' => 94,
						'dependency' => array( 'efp_carousel_mode|efp_slide_effect', '!=|not-any', 'ticker|flip,cube' ),
					),
					array(
						'id'         => 'efp_accessibility',
						'type'       => 'switcher',
						'title'      => esc_html__( 'Tab and Key Navigation', 'eventful' ),
						'subtitle'   => esc_html__( 'Enable/Disable carousel scroll with tab and keyboard.', 'eventful' ),
						'default'    => true,
						'text_on'    => esc_html__( 'Enabled', 'eventful' ),
						'text_off'   => esc_html__( 'Disabled', 'eventful' ),
						'text_width' => 94,

						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'touch_swipe',
						'type'       => 'switcher',
						'title'      => esc_html__( 'Touch Swipe', 'eventful' ),
						'subtitle'   => esc_html__( 'Enable/Disable touch swipe mode.', 'eventful' ),
						'text_on'    => esc_html__( 'Enabled', 'eventful' ),
						'text_off'   => esc_html__( 'Disabled', 'eventful' ),
						'text_width' => 94,
						'default'    => true,
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'slider_draggable',
						'type'       => 'switcher',
						'title'      => esc_html__( 'Mouse Draggable', 'eventful' ),
						'subtitle'   => esc_html__( 'Enable/Disable mouse draggable mode.', 'eventful' ),
						'text_on'    => esc_html__( 'Enabled', 'eventful' ),
						'text_off'   => esc_html__( 'Disabled', 'eventful' ),
						'text_width' => 94,
						'default'    => true,
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
					array(
						'id'         => 'slider_mouse_wheel',
						'type'       => 'switcher',
						'title'      => esc_html__( 'Mouse Wheel', 'eventful' ),
						'subtitle'   => esc_html__( 'Enable/Disable mouse wheel mode.', 'eventful' ),
						'text_on'    => esc_html__( 'Enabled', 'eventful' ),
						'text_off'   => esc_html__( 'Disabled', 'eventful' ),
						'text_width' => 94,
						'default'    => false,
						'dependency' => array( 'efp_carousel_mode', '!=', 'ticker' ),
					),
				), // End of fields array.
			)
		); // Carousel Controls section end.
	}
}
